import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import os
import torch
from models import get_model
from config import MODELS, DATASETS
from sklearn.metrics import f1_score

# --- Page Config & Custom CSS ---
st.set_page_config(page_title="NLI PIRI Diagnostics", page_icon="🔍", layout="wide")
st.markdown("""
    <style>
    /* Theme-agnostic subtle background for metrics */
    div[data-testid="stMetric"] { 
        background-color: rgba(128, 128, 128, 0.1); 
        padding: 15px; 
        border-radius: 8px; 
        border: 1px solid rgba(128, 128, 128, 0.2);
    }
    </style>
""", unsafe_allow_html=True)

# --- Helper Math Functions ---
def calculate_entropy(probs_list):
    entropies = []
    for probs in probs_list:
        p = np.array(probs)
        p = p[p > 0]
        entropies.append(-np.sum(p * np.log2(p)))
    return np.mean(entropies)

def calculate_ece(preds, probs, true_labels, n_bins=10):
    bin_boundaries = np.linspace(0, 1, n_bins + 1)
    ece = 0.0
    for i in range(n_bins):
        bin_lower, bin_upper = bin_boundaries[i], bin_boundaries[i + 1]
        confidences = np.max(probs, axis=1)
        in_bin = np.where((confidences > bin_lower) & (confidences <= bin_upper))[0]
        if len(in_bin) > 0:
            bin_acc = np.mean(np.array(preds)[in_bin] == np.array(true_labels)[in_bin])
            bin_conf = np.mean(confidences[in_bin])
            ece += np.abs(bin_acc - bin_conf) * (len(in_bin) / len(preds))
    return ece

# --- Cached Model Loader ---
@st.cache_resource(show_spinner=False)
def load_cached_model(model_key):
    return get_model(model_key)

st.title("🔍 NLI Partial Input Reliance Index (PIRI)")

# --- Sidebar Controls ---
with st.sidebar:
    st.header("⚙️ Configuration")
    selected_model = st.selectbox("Target Model", list(MODELS.keys()))
    selected_dataset = st.selectbox("Evaluation Dataset", list(DATASETS.keys()))
    selected_ablation = st.selectbox("Ablation Strategy", ["empty", "mask", "neutral", "random"])
    st.markdown("---")
    st.info("The dashboard dynamically computes metrics from the raw multi-seed CSV logs generated by the pipeline.")

# --- Main UI Tabs ---
tab1, tab2 = st.tabs(["📊 Analytical Dashboard", "🔬 Live Interpretability Probe"])

with tab1:
    csv_path = f"results/{selected_dataset}_{selected_model}_{selected_ablation}_results.csv"
    
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        
        # Isolate seed 42 for detailed probabilistic metrics
        df_seed = df[df['seed'] == df['seed'].unique()[0]]
        y_true = df_seed['gold_label'].values
        
        # Basic Accuracies
        acc_full = (df_seed['pred_full'] == y_true).mean()
        acc_hyp = (df_seed['pred_hyp_only'] == y_true).mean()
        acc_prem = (df_seed['pred_prem_only'] == y_true).mean()
        
        piri_hyp = 1 - (acc_hyp / acc_full) if acc_full > 0 else 0
        acc_gap = acc_full - acc_hyp
        
        # Advanced Metrics
        f1_hyp = f1_score(y_true, df_seed['pred_hyp_only'], average='macro')
        probs_hyp = df_seed[['prob_hyp_ent', 'prob_hyp_neu', 'prob_hyp_con']].values
        entropy_hyp = calculate_entropy(probs_hyp)
        ece_hyp = calculate_ece(df_seed['pred_hyp_only'].values, probs_hyp, y_true)

        st.subheader("Core Reliance Metrics")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Full Input Accuracy", f"{acc_full*100:.1f}%")
        c2.metric("Hyp-Only Accuracy", f"{acc_hyp*100:.1f}%", f"-{acc_gap*100:.1f}% Drop", delta_color="inverse")
        c3.metric("PIRI Score", f"{piri_hyp:.3f}")
        c4.metric("Total Samples", 1000)

        st.markdown("<br>", unsafe_allow_html=True)
        
        col_chart, col_stats = st.columns([2, 1])
        
        with col_chart:
            st.subheader("Performance Degradation")
            chart_data = pd.DataFrame({
                "Condition": ["Full Input", "Hypothesis-Only", "Premise-Only"],
                "Accuracy (%)": [acc_full*100, acc_hyp*100, acc_prem*100]
            })
            bars = alt.Chart(chart_data).mark_bar(cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                x=alt.X('Condition', sort=None, axis=alt.Axis(labelAngle=0)),
                y=alt.Y('Accuracy (%)', scale=alt.Scale(domain=[0, 100])),
                color=alt.Color('Condition', legend=None, scale=alt.Scale(scheme='set2'))
            ).properties(height=300)
            st.altair_chart(bars, use_container_width=True)
            
        with col_stats:
            st.subheader("Probabilistic Diagnostics")
            st.info(f"**Macro F1 (Hyp-Only):** {f1_hyp:.3f}\n\n*Low F1 confirms accuracy drop isn't just a class-imbalance artifact.*")
            st.warning(f"**Expected Calibration Error:** {ece_hyp:.3f}\n\n*High ECE means the model is confidently wrong on ablated inputs.*")
            st.error(f"**Average Entropy:** {entropy_hyp:.3f}\n\n*Measures certainty. Lower = more rigid shortcut exploitation.*")
            
    else:
        st.warning(f"No pipeline data found at `{csv_path}`. Run the evaluation script first.")

with tab2:
    st.subheader("Interactive Heuristic Testing")
    st.markdown("Force the model to predict on custom text and visualize the extracted `[CLS]` token attention.")
    
    premise_input = st.text_input("Premise", "A man is playing an acoustic guitar in the park.")
    hypothesis_input = st.text_input("Hypothesis", "A human is making music outdoors.")
    
    if st.button("Execute Live Probe", type="primary"):
        with st.spinner(f"Loading {selected_model.upper()} into MPS/GPU..."):
            model_instance = load_cached_model(selected_model)
            
            pred_full, probs_full = model_instance.predict(premise_input, hypothesis_input)
            
            # --- FIX: Safe Mask Token Handling for T5 ---
            if selected_ablation == "empty": 
                ab_str = ""
            elif selected_ablation == "neutral": 
                ab_str = "The entity is present."
            elif selected_ablation == "mask":
                mask_tok = getattr(model_instance.tokenizer, 'mask_token', None)
                if mask_tok is not None:
                    ab_str = " ".join([mask_tok] * 5)
                else:
                    ab_str = "<extra_id_0> <extra_id_1> <extra_id_2>" # Native T5 fallback
            else: 
                ab_str = "apple guitar window abstract train"
                
            pred_hyp, probs_hyp = model_instance.predict(ab_str, hypothesis_input)
            label_map_rev = {0: "Entailment", 1: "Neutral", 2: "Contradiction"}
            
            st.markdown("### Inference Results")
            c1, c2 = st.columns(2)
            c1.success(f"**Full Input Prediction:** {label_map_rev.get(pred_full, 'Unknown')}")
            c2.error(f"**Ablated Prediction ({selected_ablation}):** {label_map_rev.get(pred_hyp, 'Unknown')}")
            
            st.markdown("### Interpretability & Confidence")
            
            # --- FIX: Render Probabilities for Flan, Attention for Encoders ---
            if "flan" in selected_model:
                st.info(f"Attention extraction is not natively supported for {selected_model}. Showing Output Confidence instead.")
                prob_df = pd.DataFrame({"Label": ["Entailment", "Neutral", "Contradiction"], "Probability": probs_full})
                chart = alt.Chart(prob_df).mark_bar().encode(
                    x=alt.X('Label', sort=None),
                    y=alt.Y('Probability', scale=alt.Scale(domain=[0, 1])),
                    color=alt.Color('Label', legend=None)
                ).properties(height=200)
                st.altair_chart(chart, use_container_width=True)
            else:
                try:
                    _, tokens, attn = model_instance.predict_with_attention(premise_input, hypothesis_input)
                    html_str = "<div style='font-size: 18px; line-height: 1.8; font-family: monospace; padding: 15px; background: #111; border-radius: 8px; border: 1px solid #333; color: white;'>"
                    for word, score in zip(tokens, attn):
                        word_clean = word.replace('Ġ', '').replace('##', '')
                        if word_clean in ['<s>', '</s>', '[CLS]', '[SEP]', '<pad>']: continue
                        intensity = int(min(score * 255 * 5, 255))
                        bg_color = f"rgba(255, 75, 75, {intensity/255:.2f})"
                        html_str += f"<span style='background-color: {bg_color}; padding: 2px 4px; margin: 2px; border-radius: 4px;'>{word_clean}</span>"
                    html_str += "</div>"
                    st.components.v1.html(html_str, height=150)
                except Exception as e:
                    st.error(f"Attention extraction failed: {str(e)}")